//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BienesRaices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristicas_C
    {
        public int IdCaracteristica_C { get; set; }
        public Nullable<int> CanCuartos_C { get; set; }
        public Nullable<int> CanBanos_C { get; set; }
        public Nullable<int> CanGarage_C { get; set; }
        public Nullable<int> MetrosCuadradosCasa_C { get; set; }
        public Nullable<int> MetrosCuadradosLote_C { get; set; }
        public int IdPropiedad_C { get; set; }
    
        public virtual Propiedad_P Propiedad_P { get; set; }
    }
}
