
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BienesRaices.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Localizacion_L
{

    public int Id_Localizacion_L { get; set; }

    public string NombreProvincia_L { get; set; }

    public int Id_Provincia_L { get; set; }

    public string NombreCanton_L { get; set; }

    public int Id_Canton_L { get; set; }

    public string NombreDistrito_L { get; set; }

    public int Id_Distrito_L { get; set; }

    public string DireccionExacta_L { get; set; }

    public int Id_Propiedad_L { get; set; }



    public virtual Propiedad_P Propiedad_P { get; set; }

}

}
