

//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BienesRaices.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;


public partial class db_a3cb5b_webbienesraicesEntities : DbContext
{
    public db_a3cb5b_webbienesraicesEntities()
        : base("name=db_a3cb5b_webbienesraicesEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Categoria_CA> Categoria_CA { get; set; }

    public DbSet<Contacto_CO> Contacto_CO { get; set; }

    public DbSet<Credenciales_CR> Credenciales_CR { get; set; }

    public DbSet<Imagen_I> Imagen_I { get; set; }

    public DbSet<Propiedad_P> Propiedad_P { get; set; }

    public DbSet<Usuario_U> Usuario_U { get; set; }


    public virtual ObjectResult<RetornaUsuarioID_Result> RetornaUsuarioID(Nullable<int> id_Usuario)
    {

        var id_UsuarioParameter = id_Usuario.HasValue ?
            new ObjectParameter("id_Usuario", id_Usuario) :
            new ObjectParameter("id_Usuario", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaUsuarioID_Result>("RetornaUsuarioID", id_UsuarioParameter);
    }


    public virtual ObjectResult<RetornaUsuarioCorreoPwd_Result> RetornaUsuarioCorreoPwd(string usuario, string contrasena)
    {

        var usuarioParameter = usuario != null ?
            new ObjectParameter("usuario", usuario) :
            new ObjectParameter("usuario", typeof(string));


        var contrasenaParameter = contrasena != null ?
            new ObjectParameter("contrasena", contrasena) :
            new ObjectParameter("contrasena", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaUsuarioCorreoPwd_Result>("RetornaUsuarioCorreoPwd", usuarioParameter, contrasenaParameter);
    }

}

}

