
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BienesRaices.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Prioridad_Pri
{

    public Prioridad_Pri()
    {

        this.Propiedad_P = new HashSet<Propiedad_P>();

    }


    public int IdPrioridad_Pri { get; set; }

    public string Nombre_Pri { get; set; }



    public virtual ICollection<Propiedad_P> Propiedad_P { get; set; }

}

}
