//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BienesRaices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad_P
    {
        public Propiedad_P()
        {
            this.Contacto_CO = new HashSet<Contacto_CO>();
            this.Imagen_I = new HashSet<Imagen_I>();
        }
    
        public int Id_Propiedad_P { get; set; }
        public string Nombre_P { get; set; }
        public decimal Precio_P { get; set; }
        public Nullable<int> Can_Cuarto_P { get; set; }
        public Nullable<int> Can_Baños_P { get; set; }
        public string Estado_P { get; set; }
        public Nullable<int> Can_Garaje_P { get; set; }
        public int Id_Categoria_P { get; set; }
    
        public virtual Categoria_CA Categoria_CA { get; set; }
        public virtual ICollection<Contacto_CO> Contacto_CO { get; set; }
        public virtual ICollection<Imagen_I> Imagen_I { get; set; }
    }
}
