
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BienesRaices.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario_U
{

    public Usuario_U()
    {

        this.Credenciales_CR = new HashSet<Credenciales_CR>();

    }


    public int Id_Usuario_U { get; set; }

    public string Nombre_U { get; set; }

    public int Tipo_U { get; set; }



    public virtual ICollection<Credenciales_CR> Credenciales_CR { get; set; }

}

}
